# Generated by Django 5.0.7 on 2024-07-27 21:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_alter_user_options_user_image_news_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_posted_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-news_posted_at'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.TextField(verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(default='https://avatars.mds.yandex.net/i?id=33c031aed59e029b46b667c0fbedfc20a122e71b-12892682-images-thumbs&n=13', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Имя'),
        ),
    ]
