# Generated by Django 5.0.7 on 2024-08-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_news_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
