# Generated by Django 5.1 on 2024-08-14 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_news_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_to_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.news', verbose_name='К посту'),
        ),
    ]
